# See `./ContainerManager/README.md` for config options

Vpc:
  MaxAZs: 1

Domain:
  Name: !ENV ${DOMAIN_NAME}
  HostedZoneId: !ENV ${HOSTED_ZONE_ID}

AlertSubscription:
  - Email: !ENV ${EMAIL}
