
[tox]
## Configuration flags from:
# https://tox.wiki/en/latest/config.html
no_package = true

[testenv]
description = Run the tests with pytest

deps =
    -r requirements-dev.txt
    -r requirements.txt

# Setup the env vars. We want AWS creds faked, to make sure the
# test suite doesn't hit the REAL AWS. (Any aws calls should use moto).
# This also runs in it's own "venv", so your local environment will
# be restored after the tests finish.
setenv =
    ### AWS Variables
    AWS_ACCESS_KEY_ID = fake_access_key
    AWS_SECRET_ACCESS_KEY = fake_secret_key
    AWS_SHARED_CREDENTIALS_FILE = {toxinidir}/tests/fake_aws_credentials
    AWS_DEFAULT_REGION = us-west-2
    AWS_DEFAULT_PROFILE = default
    ### Example Config Variables:
    DOMAIN_NAME = example.com
    HOSTED_ZONE_ID = Z1234567890
    EMAILS = DoesNotExist@gmail.com
    SSH_IP_CIDR = 0.0.0.0/0


commands =
    # Default to the tests/ dir if no args given
    # AKA: `tox -- <pytest options>`
    pytest {tty:--color=yes} {posargs:tests/}
