---
name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug] "
labels: [ bug ]
assignees: []

body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        **⚠️ Please read this before filling out the form below:**  
        If the bug you are reporting is a security-related issue or a security vulnerability,
        please report it via [Report a security vulnerability](https://github.com/Cameronsplaze/AWS-ContainerManager/security/advisories/new) instead of this template.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        What did you expect to happen? Steps to reproduce the behavior:

        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

        Please also provide the `base-stack-config.yaml` and/or your leaf-stack config file if appropriate.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: |
        Suggest a fix/reason for the bug
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Information/Context
      description: |
        Anything else that might be relevant for troubleshooting this bug. Providing context helps us come up with a solution that is most useful in the real world.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment details (OS name and version, etc.)
      description: |
          - OS: [e.g. Ubuntu 20.04]
          - CDK Version `cdk --version`
          - Python Version `python --version`
          - Pip Environment `python3 -m pip freeze`
    validations:
        required: true

  - type: textarea
    id: other
    attributes:
      label: Other information
      description: Add any other context about the problem here.
    validations:
      required: false
