name: "Composite: Setup Python Dependencies"

description: Setup Action to python stuff

inputs:
  python-version:
    description: "Python version to use"
    required: False
    default: "3.12"

  install-packages:
    description: "Whether to install the requirements(-dev).txt packages"
    required: False
    default: "True"

runs:
  using: "composite"
  steps:

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip' # caching pip dependencies

    - name: Install Python Dependencies
      # GH ignores case when comparing strings:
      if: ${{ inputs.install-packages == 'true' }}
      shell: bash
      run: |
        make update-python
