name: "Composite: Setup Python Dependencies"

description: Setup Action to python stuff

inputs:
  python-version:
    description: "Python version to use"
    required: False
    default: "3.12"

runs:
  using: "composite"
  steps:

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip' # caching pip dependencies

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        # Pylint is apart of dev dependencies:
        python -m pip install -r requirements.txt -r requirements-dev.txt