name: "Composite: Setup Everything to use CDK"

description: Setup Action to CDK stuff

inputs: {}

runs:
  using: "composite"
  steps:

    - name: Setup Python
      uses: ./.github/workflows/composite-setup-python

    - name: Install NPM Stuff (aws-cdk)
      shell: bash
      run: |
        ### Setup NPM for non-root:
        mkdir ~/.npm-global
        npm config set prefix '~/.npm-global'
        echo "PATH=~/.npm-global/bin:$PATH" >> "$GITHUB_ENV"
        ### Update:
        make update-npm
