name: "Composite: Export GitHub Secrets/Vars"

description: "Composite: Export GitHub Secrets/Vars as Environment Variables"

inputs:
  secrets:
    description: "The secrets to export as environment variables"
    required: true
  vars:
    description: "The vars to export as environment variables"
    required: true


runs:
  using: "composite"
  steps:

    ## Setup Env Vars:
    # Taken from: https://stackoverflow.com/a/75789640/11650472
    - name: Export GitHub Secret/Vars as Shell Variables
      shell: bash
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
      run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          to_envs() { jq -r "( . // {} ) | to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\n\""; }
          echo "$VARS_CONTEXT" | to_envs >> $GITHUB_ENV
          echo "$SECRETS_CONTEXT" | to_envs >> $GITHUB_ENV
      env:
          SECRETS_CONTEXT: ${{ inputs.secrets }}
          VARS_CONTEXT: ${{ inputs.vars }}
