name: cdk-synth

on:
  workflow_dispatch: {}
  push:
    paths:
      # Any code in ContainerManager:
      - 'ContainerManager/**'
      - 'app.py'
      # Any requirements file:
      - '**/requirements*.txt'
      # This action:
      - '.github/workflows/cdk-synth-examples.yml'
      # Example Configs:
      - 'Examples/**'
      - 'base-stack-config.yaml'
      # Except any readme's / documentation:
      - '!**README.md'


env:
  EXAMPLES_PATH: ./Examples # No trailing slash plz!

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.example-config-files }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup matrix
        id: setup-matrix
        run: |
          file_list=$(cd "${{ env.EXAMPLES_PATH }}" && find * -regextype egrep -regex '.*ya?ml$')
          json_list=$(echo $file_list | jq --raw-input --compact-output 'split(" ")')
          echo "example-config-files=$json_list" >> "$GITHUB_OUTPUT"

  cdk-synth:
    # If it's NOT the main branch:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - setup-matrix
    strategy:
      matrix:
        example-config: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: ./.github/workflows/composite-setup-python

      - name: Install NPM Stuff (aws-cdk)
        run: |
          ### Setup as non-root:
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          ### Update:
          make update-npm

      - name: "Synthesize: ${{ matrix.example-config }}"
        run: make cdk-synth config-file="${{ env.EXAMPLES_PATH }}/${{ matrix.example-config }}"

  cdk-deploy:
    # If it IS the main branch:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - setup-matrix
    steps:
      - name: "test"
        run: echo TODO
