# Modified from:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request

name: Dependabot Auto-Approve PR's
on:
    pull_request: {}


permissions:
  # For Approving PR, and Auto-Merging it.
  contents: write
  pull-requests: write

jobs:

  dependabot:
    runs-on: ubuntu-latest
    # ONLY run if dependabot opens the PR:
    if: github.actor == 'dependabot[bot]'
    steps:

      - name: Approve the PR
        # https://cli.github.com/manual/gh_pr_review
        run: gh pr review "$PR_URL" --approve
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      ### This will still wait for all the REQUIRED checks to pass
      - name: Flag PR to auto-merge
        # https://cli.github.com/manual/gh_pr_merge
        run: gh pr merge "$PR_URL" --auto --merge
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Flag for Review
        if: failure()
        # https://cli.github.com/manual/gh_pr_edit
        run: gh pr edit "$PR_URL" --add-assignee "${{ github.repository_owner }}"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
