name: markdownlint - Lint Markdown Files

# Tool for linting: https://github.com/DavidAnson/markdownlint
# It's CLI: https://github.com/igorshubovych/markdownlint-cli

on:
  workflow_dispatch: {}
  pull_request:
    # Can use 'paths' here. This isn't running on dependabot updates.
    paths:
      # Changes to any markdown file:
      - '**.md'
      # Or Actions this workflow depends on (including itself):
      - '.markdownlint.yaml'
      - '.markdownlint-cli2.yaml'
      - '.github/workflows/linter-markdown.yml'

# Set minimal permissions since default is too open:
permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # Get the latest even-numbered version (their LTS):
          node-version: 'lts/*'

      - name: Install NPM Stuff (linting)
        shell: bash
        run: make update-npm-lint

      - name: Analyzing with markdownlint
        run: make lint-markdown
