name: pylint - Lint Python Files

on:
  workflow_dispatch: {}
  pull_request:
    # Can use 'paths' here. This isn't running on dependabot updates.
    paths:
      # Changes to any python file:
      - '**.py'
      # Or Actions this workflow depends on (including itself):
      - '.pylintrc'
      - '.github/workflows/linter-pylint.yml'
      - '.github/workflows/composite-setup-python/action.yaml'

# Set minimal permissions since default is too open:
permissions:
  contents: read

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: ./.github/workflows/composite-setup-python

      - name: Analyzing with pylint
        run: make lint-python
