name: markdownlint - Lint Markdown Files

# Tool for linting: https://github.com/DavidAnson/markdownlint
# It's CLI: https://github.com/igorshubovych/markdownlint-cli

on:
  workflow_dispatch: {}
  pull_request:
    # Can use 'paths' here. This isn't running on dependabot updates.
    paths:
      # Changes to any python file:
      - '**.md'
      # Or Actions this workflow depends on (including itself):
      - '.markdownlint.yaml'
      - '.github/workflows/linter-markdown.yml'

jobs:
  python-lint:
    runs-on: ubuntu-latest
    container: ghcr.io/igorshubovych/markdownlint-cli:latest
    steps:
      - uses: actions/checkout@v4

      - name: Analyzing with markdownlint
        run: markdownlint "**/*.md"
