name: Pylint

on:
  push:
    paths:
      # Changes to any python file:
      - '**.py'
      # Any requirements file:
      - '**/requirements*.txt'
      # Or Actions this workflow depends on (including itself):
      - '.pylintrc'
      - '.github/workflows/pylint.yml'
      - '.github/workflows/composite-setup-python/action.yaml'

jobs:
  python-lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.12
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: ./.github/workflows/composite-setup-python

      - name: Analysing the code with pylint
        run: |
          make pylint
