name: Pylint

on:
  push: {}
  pull_request: {}

jobs:
  python-lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.12
    steps:

    - name: Setup Python
      uses: ./.github/workflows/composite-setup-python

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
