name: Pylint

on:
  push: {}
  pull_request: {}

jobs:
  python-lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.12
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Pylint is apart of dev dependencies:
        python -m pip install -r requirements.txt -r requirements-dev.txt

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
